-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_id uuid NOT NULL,
  views integer DEFAULT 0,
  engagement_rate numeric,
  completion_rate numeric,
  performance_score integer,
  tracked_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  platform text,
  likes integer DEFAULT 0,
  shares integer DEFAULT 0,
  comments integer DEFAULT 0,
  watch_time_seconds integer,
  click_through_rate numeric,
  audience_retention jsonb DEFAULT '{}'::jsonb,
  tracked_date date NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT analytics_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);
CREATE TABLE public.asset_clips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  filename text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  duration real NOT NULL,
  resolution text DEFAULT '1920x1080'::text,
  format text DEFAULT 'mp4'::text,
  concept_tags ARRAY DEFAULT '{}'::text[],
  emotion_tags ARRAY DEFAULT '{}'::text[],
  scene_type text,
  dominant_colors ARRAY DEFAULT '{}'::text[],
  description text,
  keywords ARRAY DEFAULT '{}'::text[],
  embedding USER-DEFINED,
  quality_score real DEFAULT 5.0 CHECK (quality_score >= 1::double precision AND quality_score <= 10::double precision),
  motion_intensity text DEFAULT 'medium'::text CHECK (motion_intensity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  audio_present boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  success_rate real DEFAULT 0.0 CHECK (success_rate >= 0::double precision AND success_rate <= 1::double precision),
  processing_status text DEFAULT 'ready'::text CHECK (processing_status = ANY (ARRAY['processing'::text, 'ready'::text, 'failed'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_clips_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processing_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  video_id uuid NOT NULL,
  step text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  progress integer DEFAULT 0,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  user_id uuid,
  steps jsonb DEFAULT '[]'::jsonb,
  current_step text,
  priority integer DEFAULT 5,
  estimated_completion timestamp with time zone,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  processing_node text,
  CONSTRAINT processing_queue_pkey PRIMARY KEY (id),
  CONSTRAINT processing_queue_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id),
  CONSTRAINT processing_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text, 'enterprise'::text])),
  monthly_limit integer DEFAULT 5,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  stripe_customer_id text,
  subscription_status text DEFAULT 'inactive'::text,
  monthly_videos_used integer DEFAULT 0,
  total_videos_created integer DEFAULT 0,
  content_niche text,
  target_audience text,
  preferred_language text DEFAULT 'es'::text,
  last_video_created_at timestamp with time zone,
  brand_colors jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.templates (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  category text,
  preview_url text,
  is_premium boolean DEFAULT false,
  likes integer DEFAULT 0,
  uses integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  structure jsonb DEFAULT '{}'::jsonb,
  visual_settings jsonb DEFAULT '{}'::jsonb,
  audio_settings jsonb DEFAULT '{}'::jsonb,
  target_duration integer DEFAULT 45,
  difficulty_level text DEFAULT 'beginner'::text,
  viral_potential_score integer DEFAULT 50,
  is_active boolean DEFAULT true,
  CONSTRAINT templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_preferences (
  user_id uuid NOT NULL,
  default_template_id text,
  default_voice_id text,
  auto_enhance_script boolean DEFAULT true,
  preferred_video_length integer DEFAULT 45,
  brand_kit jsonb DEFAULT '{}'::jsonb,
  watermark_enabled boolean DEFAULT true,
  watermark_position text DEFAULT 'bottom-right'::text,
  background_music_enabled boolean DEFAULT true,
  sound_effects_enabled boolean DEFAULT true,
  voice_speed real DEFAULT 1.0,
  email_notifications boolean DEFAULT true,
  processing_complete_notifications boolean DEFAULT true,
  weekly_digest boolean DEFAULT true,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_preferences_default_template_id_fkey FOREIGN KEY (default_template_id) REFERENCES public.templates(id)
);
CREATE TABLE public.videos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  script text NOT NULL,
  template_id text NOT NULL,
  voice_id text,
  status text DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['queued'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  video_url text,
  thumbnail_url text,
  duration integer,
  settings jsonb DEFAULT '{}'::jsonb,
  analytics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  enhanced_script jsonb,
  final_script text,
  clips_used jsonb DEFAULT '[]'::jsonb,
  voice_settings jsonb DEFAULT '{}'::jsonb,
  background_music text,
  sound_effects ARRAY DEFAULT '{}'::text[],
  actual_duration real,
  file_size integer,
  processing_time integer,
  quality_score real,
  subtitles_url text,
  error_message text,
  retry_count integer DEFAULT 0,
  download_count integer DEFAULT 0,
  share_count integer DEFAULT 0,
  CONSTRAINT videos_pkey PRIMARY KEY (id),
  CONSTRAINT videos_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);